### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tonyhb** [kristiehoward/go2flow#8]
When invoking go2flow with an embedded/anonymous struct go2flow panics with a nil pointer error.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x506b57]

goroutine 1 [running]:
github.com/kristiehoward/go2flow/handlers.handleField(0x0, 0x0, 0x0, 0x0, 0x5c1a00, 0xc4200a51e0, 0x0, 0x0)
        /home/vagrant/.go/src/github.com/kristiehoward/go2flow/handlers/handlers.go:11 +0x37
github.com/kristiehoward/go2flow/handlers.HandleTypeDef(0x0, 0xc4200a51c0, 0x0, 0x5c1e40, 0xc4200a5740, 0x0)
        /home/vagrant/.go/src/github.com/kristiehoward/go2flow/handlers/handlers.go:66 +0x13e
main.TypeDefInspector(0x5c11c0, 0xc42008e900, 0xc42008a601)
        /home/vagrant/.go/src/github.com/kristiehoward/go2flow/main.go:39 +0x62
go/ast.inspector.Visit(0x5ab750, 0x5c11c0, 0xc42008e900, 0x5bffe0, 0x5ab750)
        /usr/local/go/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x5bffe0, 0x5ab750, 0x5c11c0, 0xc42008e900)
        /usr/local/go/src/go/ast/walk.go:52 +0x66
go/ast.Walk(0x5bffe0, 0x5ab750, 0x5c0c00, 0xc4200bcc00)
        /usr/local/go/src/go/ast/walk.go:331 +0xf2f
go/ast.walkDeclList(0x5bffe0, 0x5ab750, 0xc4200be400, 0x19, 0x20)
        /usr/local/go/src/go/ast/walk.go:38 +0x81
go/ast.Walk(0x5bffe0, 0x5ab750, 0x5c0ac0, 0xc4200d8280)
        /usr/local/go/src/go/ast/walk.go:353 +0x2650
go/ast.Inspect(0x5c0ac0, 0xc4200d8280, 0x5ab750)
        /usr/local/go/src/go/ast/walk.go:385 +0x4b
main.handleFile(0x7ffe5d0be577, 0xc, 0x3, 0x0)
        /home/vagrant/.go/src/github.com/kristiehoward/go2flow/main.go:52 +0xb5
main.run(0xc4200b4160, 0xc4200b4160, 0xc420047d27)
        /home/vagrant/.go/src/github.com/kristiehoward/go2flow/main.go:84 +0x211
github.com/kristiehoward/go2flow/vendor/github.com/urfave/cli.HandleAction(0x569300, 0x5ab758, 0xc4200b4160, 0xc4200b0060, 0x0)
        /home/vagrant/.go/src/github.com/kristiehoward/go2flow/vendor/github.com/urfave/cli/app.go:502 +0xc8
github.com/kristiehoward/go2flow/vendor/github.com/urfave/cli.(*App).Run(0xc4200ca000, 0xc42008e060, 0x3, 0x3, 0x0, 0x0)
        /home/vagrant/.go/src/github.com/kristiehoward/go2flow/vendor/github.com/urfave/cli/app.go:268 +0x60c
main.main()
        /home/vagrant/.go/src/github.com/kristiehoward/go2flow/main.go:100 +0x131
```

**Comment by tonyhb** [comment]
Hmm, taken a peek at the code.  It's awesomely simple.  I think in order to satisfy anonymous fields like so:


```
type Meta struct {
  Id string `json:"id"`
}

type User struct {
  Meta
  Email string `json:"email"`
}
```

We might need to do multiple passes.  One to generate type definitions for all structs without anonymous fields, and then passes to link all embedded anonymous types to their parent.

My worry is that Meta might actually be defined after User:

```
type User struct {
  Meta
  Email string `json:"email"`
}

type Meta struct {
  Id string `json:"id"`
}

```

So when parsing User we'd have no way to look up Meta's definitions, necessitating multiple passes.

This then means we can't `printft` from `handleField` - we'd need to have a map which stores type information per struct, and `handleField` should return the new type information for the given struct.

We'd then need to create a parser which loops until all fields are fully typed.

I'm a bit busy so I can't get to this now.  If I have time (and the need lolz) I'll take a look at this later.

**Comment by tonyhb** [comment]
Meh I ignored multiple passes and did something a little easier in PR #9
